{{- if .Values.auth.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prepper-backend.fullname" . }}-auth-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "prepper-backend.labels" . | nindent 4 }}
type: Opaque
data:
  APP_ADMIN_PASSWORD: {{ .Values.auth.adminPassword | b64enc | quote }}
  APP_USER_PASSWORD: {{ .Values.auth.userPassword | b64enc | quote }}
{{- end }}
