apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prepper-backend.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "prepper-backend.labels" . | nindent 4 }}
data:
  DB_URL: "jdbc:postgresql://{{ .Values.db.host }}:{{ .Values.db.port }}/{{ .Values.db.name }}"
  QUARKUS_HTTP_AUTH_BASIC: "true"
