{{- if .Values.db.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prepper-backend.fullname" . }}-db-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "prepper-backend.labels" . | nindent 4 }}
type: Opaque
data:
  DB_USER: {{ .Values.db.user | b64enc | quote }}
  DB_PASSWORD: {{ .Values.db.password | b64enc | quote }}
{{- end }}
